final_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homePage, name='homePage'),
    path('post/add/', views.addPost, name='addPost'),
    path('post/view/<int:pk>/', views.postDetail, name='postDetail'),
    path('post/delete/<int:pk>/', views.deletePost, name='deletePost'),
    path('post/edit/<int:pk>/', views.editPost, name='editPost'),

    path('user/sign-up/', views.sign_up_page, name='sign_up_page'),
    path('user/login/', views.login_page, name='login_page'),
    path('user/logout/', views.logout_request, name='logout_request'),
]

final_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('final_app.urls')),
]

final_app/models.py
from django.db import models
from datetime import datetime

class Post(models.Model):
    title = models.CharField("Title", max_length=255)
    postDate = models.DateTimeField("Published date", default=datetime.now)
    image = models.CharField("Image", max_length=500, blank=True, null=True)
    content = models.TextField("Content")

    def __str__(self):
        return f"{self.title} - {self.postDate}"

final_app/forms.py
from django import forms
from .models import Post
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'image', 'content')


class NewUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

final_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post
from .forms import AddPostForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from .forms import NewUserForm

def homePage(request):
    posts = Post.objects.all().order_by('-postDate')[:3]
    return render(request, "home.html", {
        'posts': posts
    })

def postDetail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, "user/post-detail.html", {
        'post': post
    })

def addPost(request):
    if request.method == "POST":
        form = AddPostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("homePage")
    else:
        form = AddPostForm()

    return render(request, "user/add-post.html", {
        'form': form
    })

def deletePost(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        post.delete()
        return redirect("homePage")
    return render(request, "user/delete-post.html", {
        'post': post
    })

def editPost(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = AddPostForm(request.POST or None, instance=post)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect("postDetail", pk=post.pk)
    else:
        form = AddPostForm()

    return render(request, "user/edit-post.html", {
        'post': post,
        'form': form
    })

def sign_up_page(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("login_page")

    else:
        form = NewUserForm()

    context = {'form': form}

    return render(request, "./sign-up.html", context)


def login_page(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("homePage")
    else:
        form = AuthenticationForm()
    context = {'form': form}
    return render(request, "./login.html", context)

def logout_request(request):
    logout(request)
    return redirect("homePage")

final_app/templates/all-news.html
{% extends '../base.html' %}

{% block title %}Все жалобы{% endblock %}


{% block content %}
    <div class="container">
        <h1 class="title mt-5 mb-5">Все посты</h1>
        {% for post in posts %}
        <article class="message is-info">
            <div class="message-body">
                <h3 class="title mb-3">{{ post.title }}</h3>
                <h4 class="subtitle mb-5">{{ post.postDate }}</h4>
                <p class="mb-3">{{ post.content|truncatewords:20 }}</p>
                <a href="{% url 'postDetail' pk=post.pk %}" class="button is-info">Читать</a>
            </div>
        </article>
        {% endfor %}
    </div>
{% endblock %}

final_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static './css/bulma.min.css' %}">
        <link rel="stylesheet" href="{% static './css/style.css' %}">

</head>
<body>
<div class="bag">
    <nav class="navbar is-info opac" role="navigation" aria-label="main navigation" >
        <div class="container">
            <div class="navbar-brand">
                <a class="navbar-item" href="{% url 'homePage' %}">
                    <h1 class="title has-text-white">Сайт жалоб</h1>
                </a>

                <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                </a>
            </div>

            <div id="navbarBasicExample" class="navbar-menu has-background-info">
                <div class="navbar-start">
                </div>


            <div class="navbar-end">
                        <div class="navbar-item">
                        <div class="buttons">
                            <a href="{% url 'addPost' %}" class="button is-white is-rounded">
                                Добавить жалобу
                            </a>
                        </div>
                    </div>
                    {% if user.is_authenticated %}
                  <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                      @{{ user.username }}
                    </a>

                    <div class="navbar-dropdown">
                        {% if user.is_superuser %}
                      <a class="navbar-item" href="{% url 'admin:index' %}">
                        Админ панель
                      </a>
                        {% endif %}
                      <a class="navbar-item"  href="{% url 'logout_request' %}">
                        Выход
                      </a>
                    </div>
                  </div>
                    {% else %}
                  <div class="navbar-item">
                    <div class="buttons">
                      <a class="button is rounded is-primary " href="{% url 'sign_up_page' %}">
                        <strong>Регистрация</strong>
                      </a>
                      <a class="button is rounded is-light" href="{% url 'login_page' %}">
                        Вход
                      </a>
                    </div>
                  </div>
                    {% endif %}
            </div>
            </div>
        </div>
    </nav>
</div>
    <main>
        {% block content %}

        {% endblock %}
    </main>
</body>
</html>

final_app/templates/home.html
{% extends './base.html' %}
{% block title %}Main page{% endblock %}
{% block content %}

    <div class="container">
        <div class="columns">
            <div class="card-row">
                {% for post in posts%}
                <div class="card" id="card">
                  <div class="card-content">
                      <img src="{{post.image}}" alt="title">
                    <div class="content">
                        <h3>{{post.title}}</h3>
                    </div>
                      <a href="{% url 'postDetail' pk=post.pk %}" class="button is-info">Читать полностью</a>
                  </div>
                </div>
                {%endfor%}
            </div>
        </div>
    </div>
{% endblock %}

final_app/templates/login.html
{% extends './base.html' %}
{% load crispy_forms_tags %}

{% block title %}Вход{% endblock %}

{% block content %}
<section class="block">
    <div class="container">
        <h1 class="title">Вход</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form.username|as_crispy_field }}
            </div>
            <div class="form-group">
                {{ form.password|as_crispy_field }}
            </div>
            <button type="submit" class="button is-primary is rounded">Войти</button>
            <p>Если у вас нет аккаунта, пройдите <a href="{% url 'sign_up_page' %}">регистрацию</a></p>
        </form>
    </div>
</section>

<style>
    .container {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
    }

    .title {
        text-align: center;
    }

    .form-group {
        margin-bottom: 20px;
    }


    input[type="text"],
    input[type="password"] {
        width: 100%;
        padding: 10px;
        border-radius: 5px;
        border: 1px solid #ccc;
    }

    button {
        display: block;
        width: 100%;
        padding: 10px;
        border: none;
        border-radius: 5px;
        background-color: #007bff;
        color: #fff;
        cursor: pointer;
        transition: background-color 0.3s;
    }


    p {
        text-align: center;
        margin-top: 20px;
    }

    a {
        color: #007bff;
        text-decoration: none;
    }

</style>

{% endblock %}

final_app/templates/sign-up.html
{% extends './base.html' %}
{% load crispy_forms_tags %}

{% block title %}Регистрация{% endblock %}
{% block content %}
<section class="block">
    <div class="container">
        <h1 class="title">Регистрация</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form.username|as_crispy_field }}
            </div>
            <div class="form-group">
                {{ form.email|as_crispy_field }}
            </div>
            <div class="form-group">
                {{ form.password1|as_crispy_field }}
            </div>
            <div class="form-group">
                {{ form.password2|as_crispy_field }}
            </div>
            <button type="submit" class="button is-primary is rounded">Регистрация</button>
            <p>Если у вас есть аккаунт, пройдите <a href="{% url 'login_page' %}">авторизацию</a></p>
        </form>
    </div>
</section>

<style>
    .container {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        border-radius: 10px;
    }

    .title {
        text-align: center;
    }

    .form-group {
        margin-bottom: 20px;
    }


    input[type="text"],
    input[type="email"],
    input[type="password"] {
        width: 100%;
        padding: 10px;
        border-radius: 5px;
        border: 1px solid #ccc;
    }

    button {
        display: block;
        width: 100%;
        padding: 10px;
        border: none;
        background-color: #007bff;
        color: #fff;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    button:hover {
        background-color: #0056b3;
    }

    p {
        text-align: center;
        margin-top: 20px;
    }

    a {
        color: #007bff;
        text-decoration: none;
    }
</style>

{% endblock %}

final_app/templates/user/add-post.html
{% extends '../base.html' %}
{% block title %}Add post{% endblock %}

{% block content %}
<section class="block">
    <div class="container">
        <h1 class="title mt-5 mb-5">Добавить жалобу</h1>
        <form method="post">
            {% csrf_token %}
            <div class="field">
                <label class="label">Заголовок</label>
                <div class="control">
                    <input type="text" name="title" id="id_title" class="input" placeholder="Введите заголовок" required>
                </div>
            </div>
            <div class="field">
                <label class="label">Изображение</label>
                <div class="control">
                    <input type="text" name="image" id="id_image" class="input" required>
                </div>
            </div>
            <div class="field">
                <label class="label">Содержание</label>
                <div class="control">
                    <textarea name="content" id="id_content" class="textarea" placeholder="Введите содержание" required></textarea>
                </div>
            </div>
            <div class="field is-grouped">
                <div class="control">
                    <button type="submit" class="button is-info">Добавить</button>
                </div>
            </div>
        </form>
    </div>
</section>

<style>
    .container {
        max-width: 600px;
        margin: 0 auto;
    }

    .title {
        text-align: center;
    }

    .field {
        margin-bottom: 2rem;
    }

    .label {
        font-weight: bold;
    }

    .button {
        width: 100%;
    }

    .input,
    .textarea {
        width: 100%;
        padding: 0.5rem;
        border-radius: 0.3rem;
        border: 1px solid #dbdbdb;
    }

    .textarea {
        height: 10rem;
    }
</style>
{% endblock %}

final_app/templates/user/delete-post.html
{% extends '../base.html' %}

{% block title %}Удалить продукт{% endblock %}


{% block content %}
    <div class="container">
        <form method="post">
            <h1 class="title mt-5 mb-5">Удалить заявку {{ post.title }}?</h1>
            {% csrf_token %}
            <button class="button is-danger">Да</button>
            <a href="{% url 'postDetail' pk=post.pk %}" class="button is-info">Нет</a>
        </form>
    </div>
{% endblock %}

final_app/templates/user/edit-post.html
{% extends '../base.html' %}

{% block title %}Edit post{% endblock %}

{% block content %}
<section class="block">
    <div class="container">
        <h1 class="title mt-5 mb-5">Редактировать пост</h1>
        <form method="post">
            {% csrf_token %}
            <div class="field">
                <label class="label" for="id_title">Заголовок:</label>
                <div class="control">
                    <input value="{{ post.title }}" type="text" name="title" maxlength="255" required="" id="id_title" class="input">
                </div>
            </div>
            <div class="field">
                <label class="label" for="id_image">Изображение:</label>
                <div class="control">
                    <input type="text" value="{{ post.image }}" name="image" maxlength="500" id="id_image" class="input">
                </div>
            </div>
            <div class="field">
                <label class="label" for="id_content">Содержание:</label>
                <div class="control">
                    <textarea name="content" cols="40" rows="10" required="" id="id_content" class="textarea">{{ post.content }}</textarea>
                </div>
            </div>
            <div class="field is-grouped">
                <div class="control">
                    <button class="button is-info mt-5">Изменить</button>
                </div>
            </div>
        </form>
    </div>
</section>

<style>
    .container {
        max-width: 600px;
        margin: 0 auto;
    }

    .title {
        text-align: center;
    }

    .field {
        margin-bottom: 2rem;
    }

    .label {
        font-weight: bold;
    }

    .button {
        width: 100%;
    }

    .input,
    .textarea {
        width: 100%;
        padding: 0.5rem;
        border-radius: 0.3rem;
        border: 1px solid #dbdbdb;
    }

    .textarea {
        height: 10rem;
    }
</style>
{% endblock %}

final_app/templates/user/post-detail.html
{% extends '../base.html' %}

{% block title %}{{ post.title }}{% endblock %}


{% block content %}
    <div class="container">
        <article class="mt-5 message is-info">
            <div class="message-body">
                <h3 class="title mb-5">{{ post.title }}</h3>
                <h4 class="subtitle mb-5">{{ post.postDate }}</h4>
                {% if post.image %}
                <div style="width: 100%;">
                    <img src="{{ post.image }}" alt="{{ post.title }}">
                </div>
                {% else %}
                <h2>Ничего</h2>
                {% endif %}
                <p class="mb-3">{{ post.content }}</p>
                <a href="{% url 'editPost' pk=post.pk %}" class="button is-info">Изменить</a>
                <a href="{% url 'deletePost' pk=post.pk %}" class="button is-danger">Удалить</a>
            </div>
        </article>
    </div>
{% endblock %}